config/routes.rb
Thunder::Application.routes.draw do

  root to: 'posts#search'

  resources :posts, only: [] do
    collection do
      get :search
    end
  end

end

app/models/post.rb
class Post
  include Searchable

  attr_accessor :title, :content, :path

  def initialize(attributes = {})
    attributes.each_pair do |name, value|
      send("#{name}=", value) 
    end  
  end

  def search_index_attributes
    {title: title, content: content, path: path}
  end

  def id
    title.to_s.strip 
  end

  def url
    "#{Settings.post_url_prefix}#{path}"
  end

  def self.search(query, options = {})
    size = options[:per_page] || 10
    from = ([options[:page].to_i, 1].max - 1) * size

    json = Jbuilder.encode do |j|
      j.fields [:id, :path]
      j.from from
      j.size size

      j.query do
        j.match do
          j.content do
            j.query query
            j.operator :and
          end
        end
      end
    end

    response = elasticsearch body: json

    hits = response['hits']

    total_count = hits['total']

    posts = hits['hits'].map do |hit|
      Post.new(title: hit['_id'], path: hit['fields']['path'])
    end

    Kaminari.paginate_array(posts, total_count: total_count).page(options[:page]).per(options[:per_page])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def search
    if params[:query].present?
      @posts = Post.search(params[:query], per_page: 30, page: current_page)
    end
  end

  protected

  helper_method :current_page

  def current_page
    [params[:page].to_i, 1].max
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.slim
doctype html
html lang="zh_CN"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = csrf_meta_tags
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = yield :header
    title Wiki Search
  body
    .navbar.navbar-inverse.navbar-fixed-top role="navigation"
      .container
        .navbar-header
          button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"
            span class="sr-only" Toggle navigation
            span class="icon-bar"
            span class="icon-bar"
            span class="icon-bar"
        .navbar-collapse.collapse
          = link_to 'Home', root_path, class: 'navbar-brand'
    .row
      - if flash[:notice]
        .win-row
          .alert.alert-info= flash[:notice]
      - if flash[:alert]
        .win-row
          .alert.alert-danger= flash[:alert]
      .col-md-3
        = yield :left
      .col-md-9
        = yield
    .row

app/views/posts/search.html.slim
.page-header
  h1 Search

.main-section
  = form_tag search_posts_path, class: 'form-inline', role: 'form', method: 'get' do 
    div.form-group
      = text_field_tag :query, params[:query], class: 'form-control'
    '
    div.form-group
      = submit_tag "Search", class: 'btn btn-default'
hr

- if @posts
  p
    = "共搜索到 #{@posts.total_count} 个页面, 当前显示第 #{current_page} 页。"
  .main-section.search_entries
    - @posts.each_with_index do |post|
      .entry
        = link_to post.title, post.url, target: "_blank"
  .main-section
    = paginate @posts